version: '3'

services:
  zookeeper:
    image: zookeeper
    networks:
      - gpn

  kafka:
    image: wurstmeister/kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_BROKER_ID: 1
    networks:
      - gpn

  journal-service:
    build:
      context: ./docker/sbt
      args:
        GID: $GID
        UID: $UID
    working_dir: /home/sbtuser/journal-service
    user: sbtuser
    volumes:
      - ./journal-service:/home/sbtuser/journal-service
      - ./commons:/home/sbtuser/commons
      - $USER_HOME/.sbt:/home/sbtuser/.sbt
      - $USER_HOME/.ivy2:/home/sbtuser/.ivy2
      - $USER_HOME/.cache/coursier:/home/sbtuser/.cache/coursier
    networks:
      - gpn
    ports:
    - 9008:9008
    tty: true
    command: sbt run

networks:
  gpn:
